### ISSUE TITLE
Atlas-defined time series output

### ISSUE THREAD

**Issue by benjaminsipes** [MICA-MNI/micapipe#108]
*   **What are you trying to do?**  
    * MICApipe produces only FC in the various atlases, but it does not seem to produce time series. This could be a bug, since the documentation lists the atlas parcelled time series in the list of outputs:
    `<sub>_func_space-fsnative_atlas-<parc>_desc-timeseries.txt`
    But when we run the functional processing, this is our output directory:
![MICApipe_func_output](https://github.com/MICA-MNI/micapipe/assets/87202817/0c63b9d8-ff74-4f95-833a-aacb6f5c73f9)

   There is only timeseries output for the fsLR 32k vertex space. Is there a flag that needs to be called to keep the atlas-defined time series?

    
*   **Please tell us about your computing environment:**  
    * Run with singularity container micapipe v0.2.2

**Comment by rcruces** [comment]
Hello,

First of all, our documentation is outdated for some modules and we are currently working on it. We changed `txt` to `shape.gii` because they are lighter and faster to load than `txt` files.
About the time series of the parcellated data, we removed them because it was redundant, each parcellated time series can be obtained from `fsLR-32k_desc-timeseries_clean`. 

I made a little notebook that explains how to do it on this repo [preproc_reports](https://github.com/rcruces/preproc_reports/tree/main)

jupyter notebook: [from-fsLR-32k_to-parcels.ipynb](https://github.com/rcruces/preproc_reports/blob/main/notebooks/from-fsLR-32k_to-parcels.ipynb)

best
