### ISSUE TITLE
Add wildcard to default lookup of -dwe_rpe scan?

### ISSUE THREAD

**Issue by GabrielPelletier** [MICA-MNI/micapipe#13]
*   **What is the current behaviour?** 
* If -dwi_rpe is not set, the default rpe scan is set by looking for: 
 `dwi_reverse=($(ls "${subject_bids}/dwi/${subject}${ses}"_dir-PA_*dwi.nii* 2>/dev/null))`
 and thus excludes a _dir-PA_dwi scan with a acq label set before the dir label.
(in functons/utilitise.sh at line 102)
*   **What is the motivation / use case for changing the behaviour?** 
 Seems more flexible to add a wildcard `*_dir-PA_*dwi.nii*` and should not cause issues or errors down the road (although I might be wrong about that...)
 For instance my rpe scan is named sub-08027_acq-b0_dir-PA_dwi so -proc_dwi did not find it.

**Comment by rcruces** [comment]
Hi there,
 yes, you are right, the pipeline was built initially around our [MICs database](https://portal.conp.ca/dataset?id=projects/mica-mics,) thus many of the default names are according to it . 
The flag `-dwi_rpe` should be used in those cases when the reverse phase encoding naming is different or it;s in a diferent directory (eg. `fmap`). 

We decided not to use a regex like `*_dir-PA_*dwi.nii*` because is to general and could lead to errors (it could select undesired niftis). 

I recomend you to use the flag -dwi_rpe with the full path to your file `sub-08027_acq-b0_dir-PA_dwi.nii.gz`.

You'll find further info about the proc_dwi options here: https://micapipe.readthedocs.io/en/latest/pages/02.dwiproc/index.html

And examples of usage in different dataset here: 
https://micapipe.readthedocs.io/en/latest/pages/04.databases/index.html

I hope this is useful

**Comment by GabrielPelletier** [comment]
Sounds good! Thanks
