### ISSUE TITLE
adding task fmri stream / 3dDeconvolve / to micapipe

### ISSUE THREAD

**Issue by neuroimagingdatascience** [MICA-MNI/micapipe#24]
might be great to add a task fmri stream to micapipe at one point in early 2022. We discussed this with some of you already and it may be a slight variation of the already existing rest fmri stream, and perhaps include afni's 3dDeconvolve to get beta time series that would then be mapped to the surfaces (instead of / or in addition to the preprocessed task based time series). https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dDeconvolve.html

**Comment by rcruces** [comment]
- Task fMRI stream is under development on the [devTask branch ](https://github.com/MICA-MNI/micapipe/tree/devTasks) 
- 3dDeconvolve is not implemented yet.

**Comment by rcruces** [comment]
The task processing can be perform now with the multi-acquisitions `proc_func` module. It will do motion correction, high-pass filter, geometric distortions, ICA cleaning, with FIX or tenada (if the data is multi echo) and plot the results to the surface. 
Since, `3dDeconvolve` depends on each of the task we recomend to run the `proc_func` and then do the post processing with the clean func output after, either on a surface level or at the volume level.

see the version 0.1.5 of the pipeline for more information
