### ISSUE TITLE
Independent DWI sequences are concatenated in final output when processed together.

### ISSUE THREAD

**Issue by ajschadler12** [MICA-MNI/micapipe#32]
*   **What is the current behavior?**
    1. Include two different DWI sequences. (single and multi-shell)
    2. Include two EPI images for distortion correction of respective DWI sequences.
    3. The two independent DWI sequences are concatenated into a single file, rather than two separate files.
    4. Susceptibility distortion correction (SDC) is not performed using the provided EPI image for each DWI sequence.
*   **Please provide the steps to reproduce and if possible a minimal demo of the problem**  
    1. Provide more than one separate DWI sequence using `-dwi_main`.
    2. Provide respective reverse-PE images for SDC.
*   **What is the expected behavior?**  
    1. Independent DWI sequences would be processed independently, rather than concatenated.
    2. Topup would be called using the provided, respective EPI images.
    3. The output file name would preserve the `acq-` tag from the original filename
        * i.e. `sub-01_acq-multishell_space-dwi_preproc.mif` instead of `sub-01_space-dwi_desc-dwi_preproc.mif`
*   **Please tell us about your computing environment:**  
    Ran via singularity container, `micapipe v0.1.1 'Roadrunner'`

In my case, would `proc_dwi` need to be ran on each independent DWI sequence?

**Comment by rcruces** [comment]
Hi, currently the pipeline doesn't support multiple DWI acquisition processing. It was built to process either a single shell or a multi-shell. As for the expected behaviour:

1. i. We are currently working on an extension to process multiple DWI acquisitions with different parameters (including different EPI images with their corresponding reverse phase encoding). 
2. ii. Due to the heterogeneity in datasets acquisitions even if they are BIDS conformed, we decided that the final user should provide the `rpe` and `pe` images manually, instead of hard coded it based on the naming. This behavior will be keep as it is in future releases.
3. iii. We'll include this feature in the next release where multiple acquisitions will be able to be processed.

In your case, at the present moment the option is to run each DWI sequence independently. We also encourage you to contribute with new features by forking and and pushing them to the developing branch.

thank you for using micapipe

**Comment by ajschadler12** [comment]
Thank you @rcruces . Preventing differing acquisitions processed independently from being merged in the final output could be solved if all subsequent outputs preserve the "acq-" label. I can try taking a look.

**Comment by rcruces** [comment]
We are so sorry for the very late reply. We've been working on improving the pipeline since this issue was opened.

The previous version `v0.1.5` already had a way to solve this issue including a new flag for different dwi acquisitions `-dw_acq`. Which allows the user to select only one acquisition of dwi  with `-dwi_main` and name it for example `-dwi_acq b2000`. This will create a tag and a directory for only that acquisition. Multiple acquisitions are allow for the processing. 

By default if `-dwi_main` is not declared and `-dwi_acq b2000` is not set, the pipeline will take all the shells that it finds based on pre set regular expressions `default = <bids>/<subject>/dwi/*_dir-AP_dwi.nii*`. 

This feature plus a novel QC subject- and group-based is included in our new release v0.2.0, please feel free to take a look: 
https://github.com/MICA-MNI/micapipe
