### ISSUE TITLE
2 "missing" files in QC report

### ISSUE THREAD

**Issue by mrribbits** [MICA-MNI/micapipe#42]
*   **What is the current behavior?**  
Hi! I consistently get an orange line in my workflows in my QC reports (the line is labeled ("proc_structural- proc_dwi 50").
I also consistently get a "FILE NOT FOUND" for these two files:
- "Registration: T1w in DWI space" in the proc_dwi QC module
- "Registration: FA atlas in native dwi" in the bundle segmentation QC module

I assume those two missing files are related to why the workflow line is orange (everything else in the QC reports look fine).

I think I see the "missing" files in my dwi folders (so they're not actually missing), but I'm not certain these are what it wants:
For example:
sub-02E_ses-01_space-dwi_desc-t1w_nativepro_SyN.nii.gz
sub-02E_ses-01_space-dwi_model-DTI_map-FA.mif

*   **What is the expected behavior?**  
Screenshots of these two files should appear in the QC report and the workflow line should not be orange.

*   **Please tell us about your computing environment:**  
I'm running micapipe v0.1.2 in the provided singularity container.

*   **Other information**  
The terminal output while running QC is not informative when it gets to each of these missing files:
This is the terminal output when QC gets to the missing T1w in DWI space:
`[ INFO ]..... Registration: T1w in DWI space `

And this is the terminal output when QC gets to the missing FA atlas image:
```
[ INFO ]..... Registration: FA atlas in native dwi 
Erasing temporal directory: /tmp
OLD_PATH is unset or empty
```

**Comment by PeerHerholz** [comment]
Hi @mrribbits,

sorry for the late reply. Hm, I think this could be related to #39... WDYT @rcruces?

**Comment by rcruces** [comment]
This issue is related to #39 .

Sorry for the very late reply, unfortunately the previous `-QC_subj` had two incompatibilities when it was run with docker. The first was that the absolute paths in the html QC file were broken, and also few missing libraries to generate snapshots of the surfaces were missing. We took a pragmatic decision to discontinue the support of this html based QC and we went for pdf files, based on the new `json` metadata. 

The current version solved this issues and the container was fully test to generate QC reports group and subject level. 

We invite you to try the new version `v0.2.0 Northen Flicker` which has been optimized and enhanced in many different aspects.  https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0
