### ISSUE TITLE
$dwi_dns undefined

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-MNI/micapipe#76]
line 200 of 02_proc-dwi, in the call to mrdegibbs, $dwi_dns is given as the output variable, but is not previously defined

**Comment by romainviard** [comment]
There is already a pull request to fix this bug. But as user I 'm wondering if I have to wait a new version of the container or to install micapipe in "bare-metal" fashion to get around it ?

**Comment by rcruces** [comment]
I think this issue was already fixed on the container of [`v0.1.5`](https://hub.docker.com/r/micalab/micapipe/tags).

We invite you to use the newest version of the pipeline were this issue was certanly  addressed: [`v0.2.0 Northern Flicker`](https://github.com/MICA-MNI/micapipe/releases/tag/v0.2.0)
