### ISSUE TITLE
autoTracts bundled with SC fails

### ISSUE THREAD

**Issue by araikes** [MICA-MNI/micapipe#80]
When running `-SC`, the `-autoTract` option requires the FA map. However, `03_SC.sh` still searches for the FA map as a `.mif` file, whereas this was converted to a `.nii.gz` file in `v0.1.5`.

https://github.com/MICA-MNI/micapipe/blob/d9c730d1b0b3f6c21c770d12dd9c3dba94d479f0/functions/03_SC.sh#L69

Edit:

The `autoTract` section of the code also references an undefined variable called `$fa_niigz`
https://github.com/MICA-MNI/micapipe/blob/d9c730d1b0b3f6c21c770d12dd9c3dba94d479f0/functions/03_SC.sh#L262

**Comment by rcruces** [comment]
Hello, this issue was adressed  and tested on the latest version release `v0.2.1`, which is already tagged on the github repository bbc4eabeea4fd83b8f28adb743d6b6da212af2ec  and online on the dockerhub [dockerhub](https://hub.docker.com/layers/micalab/micapipe/v0.2.1/images/sha256-7ae75a1a7621d001cc037fa0e3f9f1d3d5cc4fb2b7f2e2863eb5300de3f4b3e0?context=explore).

We thank you for your comments
