### ISSUE TITLE
Mismatch between "dependencies" and software versions

### ISSUE THREAD

**Issue by araikes** [MICA-MNI/micapipe#90]
The stated dependencies for `v0.2.2`  in Docker/Singularity do not match the installed versions for AFNI, ANTs, FSL, or Freesurfer:

```
micapipe -h

DEPENDENCIES:
    > AFNI        20.3.03 (https://afni.nimh.nih.gov/download)
    > ANTs        2.3.4   (https://github.com/ANTsX/ANTs)
    > FSL         6.0.3     (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
    > Freesurfer  7.4.0     (https://surfer.nmr.mgh.harvard.edu/)
    > MRtrix3     3.0.1   (https://www.mrtrix.org)
    > workbench   1.4.2
    > python      3.9.15
    > R           3.6.3
    > FIX         1.06    (FMRIB's ICA-based Xnoiseifier)
```

```
-------------------------------------------------------------
	Surface processing
		micapipe v0.2.2 'Northern flicker', container_micapipe-v0.2.2 
-------------------------------------------------------------

[ INFO ]..... MICA pipe - Software versions 
		MRtrix3.....	3.0.1
		            	/opt/miniconda-22.11.1/envs/micapipe/bin/mrinfo
		FSL.........	6.0
		            	/opt/fsl-6.0.2
		ANFI........	 Jun 23 2023 (Version AFNI_23.1.09 'Publius Helvius Pertinax')
		            	/opt/afni-latest/3dresample
		ANTS........	 2.3.3.dev168-g29bdf
		            	/opt/ants-2.3.4/
		WorkBench...	1.3.2
		            	/usr/bin/wb_command
		FreeSurfer..	freesurfer-linux-ubuntu18_x86_64-7.3.2-20220804-6354275
		            	/opt/freesurfer-7.3.2
		fix.........	/opt/fix1.068/fix
		            	/opt/fix1.068
		python......	3.9.16
		            	/opt/miniconda-22.11.1/envs/micapipe/bin/python
		R...........	3.6.3
		            	/usr/bin/R
		conda.......	conda 22.11.1
		            	/opt/miniconda-22.11.1/condabin/conda
```

Notable differences:
1. AFNI is 23.1.09 not 20.3.03
2. FSL is 6.0.2 (per Dockerfile) not 6.0.3
3. ANTs is 2.3.3-dev168-g29bdf not 2.3.4. I know this is the precompiled ANTs option listed for neurodocker 2.3.4 but it's not clear whether this is the official 2.3.4 release.
4. Freesurfer is 7.3.2 not 7.4

**Comment by rcruces** [comment]
Hello, indeed the dependencies were not updated, we just did it on the new container that is replacing the v0.2.2. Again since it was a typo and it does not change the behaviour  of the container we kept the same version v0.2.2.

We are using the version ANTs 2.3.4 precomplied version we took from here: 
https://github.com/kaczmarj/ANTs-builds/blob/master/README.md

You can see it on the `dockerfile`
https://github.com/MICA-MNI/micapipe/blob/6f5fc17fae8d6b43d279d18b660be22cafa79c25/Dockerfile#L206-L211

But it installs a 2.3.3_dev, for our purposes that version works properly.

Thank you once again for pointing at the issues and for using the pipeline!
